<a href="https://colab.research.google.com/github/aliyaaliyal/mesin-learning/blob/main/Kenalan_dengan_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
print(tf.__version__)

2.9.2


# Tensor

Tensor merupakan sebuah array yang berdimensi tinggi.yang merupakan komponene dasar dalam proses komputasi ANN. Tensorflow memungkinkan kita untuk melakukan operasi dan memanipulasi tensor yang berdimensi tinggi secara efisien.

# Scalar
Scalar merupakan 0-d array (tensor berorde 0) contohnya seperti 10.0

In [5]:
scalar_tensor = tf.constant(10.0)
print(scalar_tensor)

tf.Tensor(10.0, shape=(), dtype=float32)


# Vector
Vector merupakan 1d array atau sering juga disebut tensor berorde 1. contohnya [2, 3, 5, 7, 11]

In [6]:
vector_tensor = tf.constant([2, 3, 5, 7, 11])
print(vector_tensor)

tf.Tensor([ 2  3  5  7 11], shape=(5,), dtype=int32)


# Matrix
Matrix merupakan bentuk 2d array atau sering juga disebut tensor berorde 2. contoh 
[
  [3.1, 8.2, 5.9],
  [4.3, -2.7,6.5]
]


In [9]:
matrix_tensor = tf.constant(
    [
        [3.1, 8.2, 5.9],
        [4.3, -2.7,6.5]
    ]
)
print(matrix_tensor)

tf.Tensor(
[[ 3.1  8.2  5.9]
 [ 4.3 -2.7  6.5]], shape=(2, 3), dtype=float32)


# Cubes
Cubes merupakan bentuk 3d array atau tensor berorde 3. contohnya sebagai berikut


In [10]:
cube_tensor = tf.constant(
    [
        [
            [3.1, 8.2, 5.9],
            [4.3, 2.7, 6.5],
        ],
     [
          [4.5, 5.2, 3.1],
         [3.4, 2.0, 5.9],
     ],
     [
          [4.2, 3.7, 9.1],
         [6.4, 1.2, 6.4],
     ],
    ]
)
print(cube_tensor)

tf.Tensor(
[[[3.1 8.2 5.9]
  [4.3 2.7 6.5]]

 [[4.5 5.2 3.1]
  [3.4 2.  5.9]]

 [[4.2 3.7 9.1]
  [6.4 1.2 6.4]]], shape=(3, 2, 3), dtype=float32)


# Operasi tensor

In [11]:
tensor = tf.constant(3) + tf.constant(4)
print(tensor)

tf.Tensor(7, shape=(), dtype=int32)


In [12]:
print(tf.constant(3) + 4)
print(3 + tf.constant(4))

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [13]:
matrix = tf.constant([
    [11,12,13],
    [21,22,23],
    [31,32,33],
])
print(tf.transpose(matrix))

tf.Tensor(
[[11 21 31]
 [12 22 32]
 [13 23 33]], shape=(3, 3), dtype=int32)


In [17]:
matrix_one = tf.constant([
    [2, 2, 2],
    [2, 2, 2],
    [2, 2, 2],
])

matrix_two = tf.constant([
    [2, 2, 2],
    [2, 2, 2],
    [2, 2, 2],
])

tf.tensordot(matrix_one, matrix_two, axes=1)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]], dtype=int32)>

In [18]:
matrix_one = tf.constant([
    [2, 2, 2],
    [2, 2, 2],
    [2, 2, 2],
])

matrix_two = tf.constant([
    [2, 2, 2],
    [2, 2, 2],
    [2, 2, 2],
])

matrix_one * matrix_two

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]], dtype=int32)>

In [21]:
import tensorflow as tf
import numpy as np

matrix_one = tf.constant([
    [2, 2, 2],
    [2, 2, 2],
    [2, 2, 2],
])

matrix_two = tf.constant([
    [2, 2, 2],
    [2, 2, 2],
    [2, 2, 2],
])

np.dot(matrix_one, matrix_two)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]], dtype=int32)

# Membuat TensorFlow Graph untuk menyelesaikan Linear Equation
y = mx + b

In [22]:
m = tf.constant(1.0)
b = tf.constant(9.0)
X = tf.constant([-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0])
y = m*X + b

# Membuat Single Perceptron

In [23]:
X = tf.constant([-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0])
y = tf.constant([5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0])

In [24]:
model = tf.keras.Sequential([tf.keras.layers.Dense(units=1, input_shape=[1])])

In [25]:
model.compile(optimizer='sgd', loss='mean_squared_error')
model.fit(X, y, epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 562ms/step - loss: 136.7733
Epoch 2/500
1/1 [==============================] - 0s 11ms/step - loss: 114.7761
Epoch 3/500
1/1 [==============================] - 0s 8ms/step - loss: 98.8536
Epoch 4/500
1/1 [==============================] - 0s 6ms/step - loss: 87.1396
Epoch 5/500
1/1 [==============================] - 0s 7ms/step - loss: 78.3493
Epoch 6/500
1/1 [==============================] - 0s 7ms/step - loss: 71.5981
Epoch 7/500
1/1 [==============================] - 0s 8ms/step - loss: 66.2764
Epoch 8/500
1/1 [==============================] - 0s 6ms/step - loss: 61.9639
Epoch 9/500
1/1 [==============================] - 0s 8ms/step - loss: 58.3704
Epoch 10/500
1/1 [==============================] - 0s 8ms/step - loss: 55.2956
Epoch 11/500
1/1 [==============================] - 0s 6ms/step - loss: 52.6005
Epoch 12/500
1/1 [==============================] - 0s 7ms/step - loss: 50.1889
Epoch 13/500
1/1 [==========================

In [26]:
print(model.predict([-2.0, 10.0]))

1/1 [==============================] - 0s 149ms/step
[[ 6.9994254]
 [18.999828 ]]
